import { KEYWORDS, CARD_TYPES } from "./constants.js";

// カード定義は「宣言的なデータ」として持たせる。
// 固有効果(誘発・常時・超越追加効果)は effectRegistry.js 側で
// カード名をキーに後から登録する(カード追加のたびにエンジン本体を
// 書き換えずに済むようにするための分離)。
//
// cardId: スプレッドシート「カード情報」のカードID列と対応する管理用の番号。
// プレイヤーには一切表示しない。名前・効果・ステータスが大幅に変わるリメイクが
// 入っても、この番号を頼りに「これは元々どのカードの改訂版か」を追跡できるようにするため
// (テーマごとに100番台単位で区切られている: 汎用=100番台, 赤テーマ=200番台, ...)。

export const CARD_DEFS = {
  ゴブリン: { cardId: 103,
    theme: "汎用",
    effect: "効果なし。",
    name: "ゴブリン", type: CARD_TYPES.MONSTER, cost: 1, atk: 4, hp: 4,
    race: "闇", keywords: [],
  },
  ただの傭兵: { cardId: 105,
    theme: "汎用",
    effect: "効果なし。",
    name: "ただの傭兵", type: CARD_TYPES.MONSTER, cost: 2, atk: 4, hp: 8,
    race: "光", keywords: [],
  },
  リビングウォール: { cardId: 110,
    theme: "汎用",
    effect: "【挑発】",
    name: "リビングウォール", type: CARD_TYPES.MONSTER, cost: 5, atk: 0, hp: 20,
    race: "闇", keywords: [KEYWORDS.CHOUHATSU],
  },
  天翔ける騎士: { cardId: 112,
    theme: "汎用",
    effect: "【速攻】【確殺】",
    name: "天翔ける騎士", type: CARD_TYPES.MONSTER, cost: 6, atk: 16, hp: 16,
    race: "光", keywords: [KEYWORDS.SOKKOU, KEYWORDS.KAKUSATSU],
  },
  死神: { cardId: 113,
    theme: "汎用",
    effect: "【貫通】",
    name: "死神", type: CARD_TYPES.MONSTER, cost: 9, atk: 32, hp: 4,
    race: "闇", keywords: [KEYWORDS.KANTSUU],
  },
  投石: { cardId: 101, name: "投石", type: CARD_TYPES.EVENT, cost: 1 , theme: "汎用", effect: "相手モンスター1体に4ダメージ。" },
  やり直し: { cardId: 102, name: "やり直し", type: CARD_TYPES.EVENT, cost: 1 , theme: "汎用", effect: "カードを1枚ドローする。" },
  祈り: { cardId: 104, name: "祈り", type: CARD_TYPES.EVENT, cost: 1 , theme: "汎用", effect: "自分の体力を4回復する。" },
  痛いのは嫌なので: { cardId: 106, name: "痛いのは嫌なので", type: CARD_TYPES.EVENT, cost: 2 , theme: "汎用", effect: "自分のシールド値を8上げる。" },
  用意周到: { cardId: 107, name: "用意周到", type: CARD_TYPES.EVENT, cost: 3 , theme: "汎用", effect: "自分の手札1枚に「保留」を付与する。" },
  明日から本気出す: { cardId: 108, name: "明日から本気出す", type: CARD_TYPES.EVENT, cost: 3 , theme: "汎用", effect: "ストレージのカードをすべてデッキに戻す。" },
  シールドバッシュ: { cardId: 111, name: "シールドバッシュ", type: CARD_TYPES.EVENT, cost: 5 , theme: "汎用", effect: "相手のシールド値を0にする。" },
  福音受けし者: { cardId: 109,
    theme: "汎用",
    effect: "場に出たとき、相手の場にいるモンスターすべてに4ダメージ。≪超越≫相手の場にいるモンスター1体を破壊する。",
    name: "福音受けし者", type: CARD_TYPES.MONSTER, cost: 3, atk: 8, hp: 8,
    race: "光", keywords: [],
  },

  // --- 赤テーマ(仮) ---
  ドラゴンの卵: { cardId: 202,
    theme: "赤",
    effect: "攻撃できない。",
    name: "ドラゴンの卵", type: CARD_TYPES.MONSTER, cost: 1, atk: 0, hp: 12,
    race: "ドラゴン", keywords: [], cannotAttack: true,
  },
  ワイバーン: { cardId: 203,
    theme: "赤",
    effect: "効果なし。",
    name: "ワイバーン", type: CARD_TYPES.MONSTER, cost: 1, atk: 8, hp: 4,
    race: "亜竜", keywords: [],
  },
  洞窟を守る地竜: { cardId: 208,
    theme: "赤",
    effect: "【挑発】《超越》自分の場に『洞窟を守る地竜』2体を特殊召喚する。",
    name: "洞窟を守る地竜", type: CARD_TYPES.MONSTER, cost: 2, atk: 4, hp: 12,
    race: "亜竜", keywords: [KEYWORDS.CHOUHATSU],
  },
  エリマキドラゴン: { cardId: 209,
    theme: "赤",
    effect: "場に出たとき、カードを1枚ドローする。",
    name: "エリマキドラゴン", type: CARD_TYPES.MONSTER, cost: 2, atk: 8, hp: 8,
    race: "ドラゴン", keywords: [],
  },
  老練の竜使い: { cardId: 211,
    theme: "赤",
    effect: "手札から召喚したとき、場に存在するドラゴン種を+8/0する。≪超越≫自分の場にいるドラゴン・亜竜種1体に【貫通】を付与する。",
    name: "老練の竜使い", type: CARD_TYPES.MONSTER, cost: 3, atk: 12, hp: 4,
    race: "竜人", keywords: [],
  },
  レッドドラゴン: { cardId: 212,
    theme: "赤",
    effect: "【突撃】①召喚するとき、自分の場にある『ドラゴンの卵』を墓地に送らなければならない。②場に出たとき、相手の場にいるモンスター1体に16ダメージを与える。",
    name: "レッドドラゴン", type: CARD_TYPES.MONSTER, cost: 3, atk: 16, hp: 8,
    race: "ドラゴン", keywords: [KEYWORDS.TOTSUGEKI],
    releaseRequirement: "ドラゴンの卵",
  },
  ブルードラゴン: { cardId: 213,
    theme: "赤",
    effect: "【挑発】①召喚するとき、自分の場にある『ドラゴンの卵』を墓地に送らなければならない。②場に出たとき、相手の場にいるモンスターすべてに8ダメージを与える。",
    name: "ブルードラゴン", type: CARD_TYPES.MONSTER, cost: 3, atk: 8, hp: 16,
    race: "ドラゴン", keywords: [KEYWORDS.CHOUHATSU],
    releaseRequirement: "ドラゴンの卵",
  },
  スピア・ワイバーン: { cardId: 214,
    theme: "赤",
    effect: "【貫通】【速攻】",
    name: "スピア・ワイバーン", type: CARD_TYPES.MONSTER, cost: 3, atk: 12, hp: 8,
    race: "亜竜", keywords: [KEYWORDS.KANTSUU, KEYWORDS.SOKKOU],
  },
  クロデカス・ワイバーン: { cardId: 216,
    theme: "赤",
    effect: "手札から召喚されたとき、自分の場にワイバーン2体を特殊召喚する。自分の場にいるワイバーンは【速攻】を持つ。",
    name: "クロデカス・ワイバーン", type: CARD_TYPES.MONSTER, cost: 4, atk: 8, hp: 12,
    race: "亜竜", keywords: [],
  },
  右腕を失くしたゴ・ド・リック: { cardId: 219,
    theme: "赤",
    effect: "場に出たとき『ゴ・ド・リックの右腕』を特殊召喚する。それは、【挑発】を持つ。≪超越≫『ゴ・ド・リックの右腕』を+8/+4し、【突撃】を付与する。",
    name: "右腕を失くしたゴ・ド・リック", type: CARD_TYPES.MONSTER, cost: 5, atk: 16, hp: 12,
    race: "竜人", keywords: [],
  },
  ゴ・ド・リックの右腕: { cardId: 220,
    theme: "赤",
    effect: "『右腕を失くしたゴ・ド・リック』が自分の場から離れたとき、このカードを破壊する。",
    name: "ゴ・ド・リックの右腕", type: CARD_TYPES.MONSTER, cost: 5, atk: 4, hp: 20,
    race: "ドラゴン", keywords: [], copyLimit: 0, // デッキ投入不可、特殊召喚専用
  },
  ドラゴニュート・キング: { cardId: 223,
    theme: "赤",
    effect: "【隠密】【突撃】①場に出たとき、デッキから竜人種1体を手札に加える。②1ターンに1度、敵を破壊したとき、もう一度攻撃できるようになる。≪超越≫敵を破壊したとき、相手に8ダメージを与える。",
    name: "ドラゴニュート・キング", type: CARD_TYPES.MONSTER, cost: 7, atk: 20, hp: 16,
    race: "竜人", keywords: [KEYWORDS.ONMITSU],
  },
  竜餐の祭日: { cardId: 201, name: "竜餐の祭日", type: CARD_TYPES.EVENT, cost: 0 , theme: "赤", effect: "ドラゴン種が戦闘によってモンスターを破壊したターンに使用できる。カードを1枚ドローする。" },
  ドラゴンの血誓: { cardId: 204, name: "ドラゴンの血誓", type: CARD_TYPES.EVENT, cost: 1 , theme: "赤", effect: "手札のドラゴン種1体を墓地に送ることで発動可能。デッキから2枚ドローする。" },
  リバーススケイル: { cardId: 205, name: "リバーススケイル", type: CARD_TYPES.EVENT, cost: 1 , theme: "赤", effect: "自分の場に存在する亜竜・ドラゴン種1体の攻撃力をターン終了時まで8アップする。" },
  ドラゴンの招集: { cardId: 206, name: "ドラゴンの招集", type: CARD_TYPES.EVENT, cost: 2 , theme: "赤", effect: "自分の場にドラゴン種のモンスターがいるときに発動可能。墓地にある亜竜種2体をデッキに戻す。" },
  滝の試練: { cardId: 207, name: "滝の試練", type: CARD_TYPES.EVENT, cost: 2 , theme: "赤", effect: "手札を1枚捨てることで発動可能。デッキ・ストレージからドラゴン種1体を手札に加える。" },
  エッグ・シーフ: { cardId: 210,
    theme: "赤",
    effect: "①場に出たとき、デッキ・ストレージから『ドラゴンの卵』1枚を手札に加える。②場から離れたとき、墓地にある『ドラゴンの卵』をすべてデッキに加える。",
    name: "エッグ・シーフ", type: CARD_TYPES.MONSTER, cost: 2, atk: 8, hp: 4,
    race: "盗賊", keywords: [],
  },
  ドラゴンの眼光: { cardId: 215, name: "ドラゴンの眼光", type: CARD_TYPES.EVENT, cost: 3 , theme: "赤", effect: "自分の場にドラゴン種がいるとき、相手の場にいるモンスター1体を破壊できる。" },
  デスラトル: { cardId: 217, name: "デスラトル", type: CARD_TYPES.EVENT, cost: 4 , theme: "赤", effect: "自分の場・手札から亜竜種2体を墓地に送ることで発動可能。相手の場にいるモンスター2体に16ダメージを与える。" },
  オルレアホワイト・ドラゴン: { cardId: 218,
    theme: "赤",
    effect: "①召喚するとき、自分の場にある『ドラゴンの卵』を墓地に送らなければならない。②1ターンに1度発動可能。手札からドラゴン種1体を除外する。ターン終了時まで攻撃力が、除外したモンスターの攻撃力分アップする。③自分のエンドフェイズ時、相手の場にいる、このモンスターの攻撃力より体力が低いモンスターを破壊する。≪超越≫カードを2枚ドローする。",
    name: "オルレアホワイト・ドラゴン", type: CARD_TYPES.MONSTER, cost: 5, atk: 4, hp: 20,
    race: "ドラゴン", keywords: [], releaseRequirement: "ドラゴンの卵",
  },
  ダリアバーミリオン・ドラゴン: { cardId: 221,
    theme: "赤",
    effect: "【速攻】①召喚するとき、自分の場にある『レッドドラゴン』を墓地に送らなければならない。②場に出たとき、相手の場にいるモンスター1体に24ダメージを与える。その後、自分の場にいる亜竜種すべてに「速攻」を付与する。≪超越≫自分のエンドフェイズ時、相手プレイヤーに20ダメージ与える。",
    name: "ダリアバーミリオン・ドラゴン", type: CARD_TYPES.MONSTER, cost: 6, atk: 24, hp: 16,
    race: "ドラゴン", keywords: [KEYWORDS.SOKKOU], releaseRequirement: "レッドドラゴン",
  },
  デルフィニウムアズール・ドラゴン: { cardId: 222,
    theme: "赤",
    effect: "【挑発】①召喚するとき、自分の場にある『ブルードラゴン』を墓地に送らなければならない。②場に出たとき、相手の場にいるモンスターすべてに12ダメージを与える。その後、墓地にいる亜竜種1体を「挑発」を付与した状態で自分の場に特殊召喚できる。≪超越≫自分のエンドフェイズ時、プレイヤーの体力を24回復する。",
    name: "デルフィニウムアズール・ドラゴン", type: CARD_TYPES.MONSTER, cost: 6, atk: 12, hp: 28,
    race: "ドラゴン", keywords: [KEYWORDS.CHOUHATSU], releaseRequirement: "ブルードラゴン",
  },
  エンダーリコリス・ワイバーン: { cardId: 224,
    theme: "赤",
    effect: "【速攻】①このカードは特殊召喚できない。②場に出たとき、墓地の亜竜種を2体まで自分の場に特殊召喚できる。≪超越≫自分の場にいる亜竜種を+8/+4し、【挑発】を付与する。",
    name: "エンダーリコリス・ワイバーン", type: CARD_TYPES.MONSTER, cost: 8, atk: 28, hp: 28,
    race: "亜竜", keywords: [KEYWORDS.SOKKOU], cannotBeSpecialSummoned: true,
  },

  // --- クレリックテーマ(友人考案) ---
  忠義の騎士ジル・ド・レェ: { cardId: 301,
    theme: "クレリック",
    effect: "【挑発】①自分の場に「聖女」がいるとき、このカードは戦闘以外でダメージを受けず、効果で破壊されない。②このカードの攻撃力が自分の墓地のジャンヌの枚数×4分アップする。",
    name: "忠義の騎士ジル・ド・レェ", type: CARD_TYPES.MONSTER, cost: 1, atk: 4, hp: 4,
    race: "騎士", keywords: [KEYWORDS.CHOUHATSU],
  },
  神託の修道士: { cardId: 302,
    theme: "クレリック",
    effect: "このカードが場に出た時、自分のHPを8回復する。自分のHPが最大であるときは1ドローする。",
    name: "神託の修道士", type: CARD_TYPES.MONSTER, cost: 1, atk: 4, hp: 8,
    race: "神官", keywords: [],
  },
  天啓の聖女ジャンヌ・ダルク: { cardId: 303,
    theme: "クレリック",
    effect: "①自分の場にいるこのカード以外のモンスターの攻撃力を、このカードが場に存在する限り4アップする。この効果は重複する。《超越》このカードは+12/+12され、1ターンに2回攻撃できるようになる。",
    name: "天啓の聖女ジャンヌ・ダルク", type: CARD_TYPES.MONSTER, cost: 2, atk: 8, hp: 8,
    race: "騎士・聖女", keywords: [],
  },
  神の啓示: { cardId: 304, name: "神の啓示", type: CARD_TYPES.EVENT, cost: 2, theme: "クレリック", effect: "ストレージからカードを1枚選び、デッキの一番上に置く。次のターン、そのカードのコストを-3する。" },
  聖騎士ライル: { cardId: 305,
    theme: "クレリック",
    effect: "【突撃】このカードが攻撃によって敵を破壊したとき、1枚ドローする。",
    name: "聖騎士ライル", type: CARD_TYPES.MONSTER, cost: 3, atk: 12, hp: 8,
    race: "騎士", keywords: [KEYWORDS.TOTSUGEKI],
  },
  聖女カトリーヌ: { cardId: 306,
    theme: "クレリック",
    effect: "【挑発】場に出たとき、デッキ・ストレージからコスト2以下の「聖女」1枚を手札に加えることができる。",
    name: "聖女カトリーヌ", type: CARD_TYPES.MONSTER, cost: 3, atk: 4, hp: 16,
    race: "聖女", keywords: [KEYWORDS.CHOUHATSU],
  },
  オルレアンの民兵: { cardId: 307,
    theme: "クレリック",
    effect: "【突撃】【確殺】手札から場に出た時、『オルレアンの民兵』1枚を自分の場に出す。",
    name: "オルレアンの民兵", type: CARD_TYPES.MONSTER, cost: 4, atk: 12, hp: 12,
    race: "民兵", keywords: [KEYWORDS.TOTSUGEKI, KEYWORDS.KAKUSATSU],
  },
  聖旗: { cardId: 308, name: "聖旗", type: CARD_TYPES.EVENT, cost: 5, theme: "クレリック", effect: "『天啓の聖女ジャンヌ・ダルク』1体と『忠義の騎士ジル・ド・レェ』1体を自分の場に出す。4ターン目以降にこの効果で特殊召喚された『天啓の聖女ジャンヌ・ダルク』は《超越》する。" },
  大天使ミカエル: { cardId: 309,
    theme: "クレリック",
    effect: "場に出た時、敵のモンスター1体を破壊する。自分のHPを16回復する。",
    name: "大天使ミカエル", type: CARD_TYPES.MONSTER, cost: 5, atk: 12, hp: 16,
    race: "天使", keywords: [],
  },
  異端審問官コーション: { cardId: 310,
    theme: "クレリック",
    effect: "このカードは自分の場、手札から『天啓の聖女ジャンヌ・ダルク』を墓地に送ることで特殊召喚できる。場に出たとき、相手の場にいるモンスターをすべて破壊する。そして相手のHPに破壊したモンスターの数×4ダメージ与える。",
    name: "異端審問官コーション", type: CARD_TYPES.MONSTER, cost: 7, atk: 20, hp: 12,
    race: "神官", keywords: [], sacrificeRequirement: "天啓の聖女ジャンヌ・ダルク",
  },
  火刑に処されし聖女: { cardId: 311,
    theme: "クレリック",
    effect: "このカードが場に出たとき、自分の墓地の『天啓の聖女ジャンヌ・ダルク』の枚数によって以下の効果を発動できる。1枚以上なら、敵のモンスターを1体選び破壊する。2枚以上なら、このカードを+4/+4する。3枚以上なら、『忠義の騎士ジル・ド・レェ』1体を自分の場に出す。4枚以上なら、このカードは【速攻】を持つ。《超越》相手のHPに20ダメージ与える。",
    name: "火刑に処されし聖女", type: CARD_TYPES.MONSTER, cost: 9, atk: 28, hp: 28,
    race: "聖女", keywords: [],
  },
};

export function createCardInstance(defName, ownerId, instanceId) {
  const def = CARD_DEFS[defName];
  if (!def) throw new Error(`未定義のカードです: ${defName}`);
  return {
    instanceId,
    ownerId,
    defName: def.name,
    type: def.type,
    cost: def.cost,
    race: def.race ?? null,
    baseAtk: def.atk ?? 0,
    baseHp: def.hp ?? 0,
    currentAtk: def.atk ?? 0,
    currentHp: def.hp ?? 0,
    cannotAttack: !!def.cannotAttack,
    baseKeywords: new Set(def.keywords ?? []),
    grantedKeywords: new Set(), // カード効果で後から付与。場を離れると自動消滅(インスタンス破棄で自然に達成)
    summonedOnTurn: null,       // グローバルターン数
    hasAttackedThisTurn: false,
    transcended: false,
    invulnerableThisTurn: false,
    attackRestriction: null,    // 'monsterOnly' 等、そのターン限定の攻撃制限
    canBeSpecialSummoned: !def.cannotBeSpecialSummoned,
    onceEffectUsedThisTurn: {}, // 「1ターンに1度」系の個別フラグ置き場
    tempAtkThisTurn: 0, // 「ターン終了時まで」の一時的な攻撃力バフ(例:リバーススケイル)。endTurn()で自動的に元に戻す
    tempHpThisTurn: 0,  // 同上、体力版
    usedDoubleAttackThisTurn: false, // 天啓の聖女ジャンヌ・ダルク《超越》の2回攻撃用(1ターンに1度だけ再攻撃可能にする)
  };
}
